### ISSUE TITLE
Unable to sign CLA

### ISSUE THREAD

**Issue by jamime** [JSFoundation/js.foundation#21]
There is no option to sign the CLA/CCLA.

**Comment by kborchers** [comment]
Hi @jamime. You will be presented with the opportunity to sign the CLA when you contribute to a project. Upon your first PR, our bot will comment with a link where you can sign the CLA for that project.

**Comment by jamime** [comment]
We should document this on the CLA page, no one in #dojo, #jquery or #jquery-dev knew.
