### ISSUE TITLE
Links in the text of the CLA assistant aren't clearly visible, have the same style as the text.

### ISSUE THREAD

**Issue by sompylasar** [JSFoundation/js.foundation#28]
![Links in the text of the CLA assistant aren't clearly visible, have the same style as the text.](https://cloud.githubusercontent.com/assets/498274/25078773/407f0ecc-22eb-11e7-8ef8-68b9c30768a1.gif)

**Comment by kborchers** [comment]
Thank you for the report! This will be updated on the next application deployment.
