### ISSUE TITLE
trainwreck membership signup form on iOS

### ISSUE THREAD

**Issue by boneskull** [JSFoundation/js.foundation#29]
![img_3435](https://cloud.githubusercontent.com/assets/924465/25654901/be2ef1ca-2fa7-11e7-9108-e9ca7275efa2.PNG)

**Comment by boneskull** [comment]
I, of course, mean that in the nicest way possible

**Comment by kborchers** [comment]
Thanks! I have the creative team looking into fixing that now and will update this issue once fixed.

**Comment by kborchers** [comment]
This should now be corrected. Would you mind verifying on your device? Thank you!

**Comment by boneskull** [comment]
looks good
