### ISSUE TITLE
Code of Conduct: "Original text courtesy of the Speak Up! project and Django Project."

### ISSUE THREAD

**Issue by platinumazure** [JSFoundation/js.foundation#33]
I was reading the Code of Conduct and I wanted to ask about a possible ambiguous attribution.

Specifically, the following text appears at the end of the "When we disagree, try to understand why" section:

> Original text courtesy of the Speak Up! project and Django Project.

Given how the rest of the page is laid out (i.e., with colored borders between each section), this suggests that the text only applies to the "When we disagree, try to understand why" section. However, this is also the last section (before "Questions?") on the page, so I wanted to make sure that this was intentional. Another possibility is that this attribution is supposed to apply to the entire page (i.e., that the entire Code of Conduct was derived from Speak Up! and Django).

If the attribution is supposed to apply to the whole page, then I think it would make sense to move the text to after the "Questions?" section, even if that bit isn't itself derived from Speak Up! and Django. If nothing else, maybe it should go after the colored border but before the "Questions?" header. Or, if the attribution is supposed to apply only to the "When we disagree, try to understand why" section, then it's fine as it is, but could possibly be improved by adding a footnote section which provides proper attribution for the different sections.

**Comment by kborchers** [comment]
Thanks! We have updated the layout. Let us know if that does not address your concern.

**Comment by platinumazure** [comment]
Looks good to me, thanks so much for addressing this!
